### ISSUE TITLE
Feat: include JRE in the Appimage

### ISSUE THREAD

**Issue by cyrneko** [unmojang/FjordLauncher#6] opened 2024-05-20 18:39 UTC
### Role

I play Minecraft, I cannot add a Java Runtime to my host system.

### Suggestion

I want the Fjord AppImage to include the JRE (or have optional builds with it) 

### Benefit

so that Immutable Systems can use the AppImage. E.g something like Fedora Silverblue where adding packages to the system image is discouraged.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by evan-goode** [comment] 2024-05-27 16:13
I recently set up a Flatpak repository, try that: https://github.com/unmojang/FjordLauncher#flatpak.

Otherwise, I'm going to close this, IMO the AppImage should not contain its own JRE, the Silverblue use case is a bit of an outlier, and the Flatpak should work there. Besides, this would be a deviation from upstream that isn't really relevant to this fork. If you can reproduce the issue on upstream Prism Launcher (you should be able to, unless they have changed this since the last release), feel free to open an issue there, and Fjord will get those changes next time we sync with upstream.

**Closed as completed by evan-goode** 2024-05-27 16:13 UTC
Labels: enhancement
